apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: nodejs-k8s-deployment
spec:
  selector:
    matchLabels:
      app: nodejs-k8s
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: nodejs-k8s
    spec:
      containers:
        - name: nodejs-k8s
          image: 957288871734.dkr.ecr.ap-southeast-1.amazonaws.com/images:$BUILD_NUMBER' # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: nodejs-k8ssvc
spec:
  selector:
    app: nodejst-k8s
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: NodePort # type of the service.
